# Podman Compose configuration for Spending Transaction Monitor
# Uses IMAGE_TAG environment variable to control which image tags to use:
# - IMAGE_TAG=latest (default): Uses images from quay.io registry
# - IMAGE_TAG=local: Uses locally built images tagged as 'local'
services:
  postgres:
    image: docker.io/pgvector/pgvector:pg16
    platform: linux/amd64
    container_name: postgres
    env_file:
      - .env.development
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d spending-monitor"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - spending-monitor

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    platform: linux/amd64
    container_name: spending-monitor-keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_PORT=8080
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
      - KC_HEALTH_ENABLED=true
      - KC_HOSTNAME=localhost
      - KC_HOSTNAME_PORT=8080
      - KC_HOSTNAME_URL=http://localhost:8080
    ports:
      - "8080:8080"
    command: start-dev
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 60s
    networks:
      - spending-monitor

  migrations:
    #image: quay.io/rh-ai-quickstart/spending-monitor-db:${IMAGE_TAG:-latest}
    image: spending-monitor-db:${IMAGE_TAG:-latest}
    platform: linux/amd64
    container_name: spending-monitor-migrations
    env_file:
      - .env.development
    environment:
      # Override KEYCLOAK_URL to use internal container name
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=spending-monitor
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DEFAULT_PASSWORD=password123
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    networks:
      - spending-monitor

  # SMTP Server for testing (smtp4dev)
  smtp4dev:
    image: docker.io/rnwood/smtp4dev:latest
    platform: linux/amd64
    container_name: spending-monitor-smtp
    ports:
      - "3002:80"   # Web UI
      # smtp4dev listens on port 25 for incoming SMTP traffic.
      # Uncomment the following line to also accept SMTP traffic from the host on port 2525.
      - "2525:25"
    networks:
      - spending-monitor

  # FastAPI Backend
  api:
    # image: quay.io/rh-ai-quickstart/spending-monitor-api:${IMAGE_TAG:-latest}
    image: spending-monitor-api:${IMAGE_TAG:-latest}
    platform: linux/amd64
    build:
      context: .
      dockerfile: packages/api/Containerfile
    container_name: spending-monitor-api
    env_file:
      - .env.development
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
      smtp4dev:
        condition: service_started
    networks:
      - spending-monitor
    volumes:
      - ./data:/app/data

  # React Frontend
  ui:
    #image: quay.io/rh-ai-quickstart/spending-monitor-ui:${IMAGE_TAG:-latest}
    image: spending-monitor-ui:${IMAGE_TAG:-latest}
    platform: linux/amd64
    build:
      context: .
      dockerfile: packages/ui/Containerfile
    container_name: spending-monitor-ui
    env_file:
      - .env.development
    depends_on:
      - api
    networks:
      - spending-monitor

  # Nginx reverse proxy to serve UI and proxy API
  nginx:
    image: docker.io/library/nginx:alpine
    platform: linux/amd64
    container_name: spending-monitor-nginx
    ports:
      - "3000:80"
    depends_on:
      - ui
      - api
    networks:
      - spending-monitor
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  llamastack:
    image: docker.io/llamastack/distribution-starter:latest
    platform: linux/amd64
    container_name: spending-monitor-llamastack
    env_file:
      - .env.development
    ports:
      - "8321:8321"
    networks:
      - spending-monitor
    volumes:
      - ./run-config.yaml:/run-config.yaml
    entrypoint: python
    command: ["-m", "llama_stack.core.server.server", "/run-config.yaml"]

  # Optional: pgAdmin for database management  
  pgadmin:
    image: docker.io/dpage/pgadmin4:latest
    platform: linux/amd64
    container_name: spending-monitor-pgadmin
    env_file:
      - .env.development
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8081:80"  # Changed from 8080 to avoid conflict with Keycloak
    depends_on:
      - postgres
    networks:
      - spending-monitor
    profiles:
      - tools  # Only start with --profile tools

networks:
  spending-monitor:
    driver: bridge

volumes:
  postgres_data: