# Production values - Keycloak Auth Mode
# Use with: helm install -f values-prod-keycloak.yaml
# IMPORTANT: Override secrets via --set or external secret management

# Override secrets for production with Keycloak
secrets:
  ENVIRONMENT: "production"
  DEBUG: "false"
  BYPASS_AUTH: "false"
  
  # Database - MUST be overridden with secure values
  POSTGRES_DB: "spending-monitor"
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "CHANGE-ME-SECURE-PASSWORD"
  DATABASE_URL: "postgresql+asyncpg://user:CHANGE-ME@spending-monitor-db:5432/spending-monitor"
  
  # LLM Configuration - MUST be overridden
  LLM_PROVIDER: "openai"
  BASE_URL: "https://api.openai.com/v1"
  API_KEY: "CHANGE-ME-REAL-API-KEY"
  MODEL: "gpt-3.5-turbo"
  
  # CORS - should be set to actual route URL after first deploy
  CORS_ALLOWED_ORIGINS: "*"
  ALLOWED_ORIGINS: "*"
  
  # SMTP - MUST be configured for email notifications
  SMTP_HOST: "CHANGE-ME-smtp.example.com"
  SMTP_PORT: "587"
  SMTP_FROM_EMAIL: "noreply@example.com"
  SMTP_USE_TLS: "true"
  SMTP_USE_SSL: "false"
  
  # Keycloak - MUST be configured
  KEYCLOAK_URL: "http://spending-monitor-keycloak:8080"
  KEYCLOAK_REALM: "spending-monitor"
  KEYCLOAK_CLIENT_ID: "spending-monitor"
  
  # UI
  VITE_API_BASE_URL: "/api"

# Production resource allocations
api:
  replicas: 2
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

ui:
  replicas: 2
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"

ingestion:
  enabled: true
  replicas: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# Persistent storage for production
database:
  persistence:
    enabled: true
    size: 50Gi
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

# Migration resources
migration:
  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "500m"

