"""add_sms_notifications_enabled_to_users

Revision ID: ce6f63eda61e
Revises: 4a13a47c8ec1
Create Date: 2026-01-26 14:35:34.086889

"""

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = 'ce6f63eda61e'
down_revision = '4a13a47c8ec1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'cached_recommendations',
        'generated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'cached_recommendations',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'cached_recommendations',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'merchant_category_embeddings',
        'embedding',
        existing_type=Vector(1536),
        type_=Vector(384),
        existing_nullable=False,
    )
    op.add_column(
        'users',
        sa.Column(
            'sms_notifications_enabled',
            sa.Boolean(),
            server_default=sa.text('true'),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sms_notifications_enabled')
    op.alter_column(
        'merchant_category_embeddings',
        'embedding',
        existing_type=Vector(384),
        type_=Vector(1536),
        existing_nullable=False,
    )
    op.alter_column(
        'cached_recommendations',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'cached_recommendations',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'cached_recommendations',
        'generated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    # ### end Alembic commands ###
