{{- if .Values.ingestion.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ingestion.name }}
  labels:
    {{- include "spending-monitor.ingestion.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ingestion.replicas }}
  selector:
    matchLabels:
      {{- include "spending-monitor.ingestion.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "spending-monitor.ingestion.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "spending-monitor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: ingestion
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "spending-monitor.image" (dict "name" .Values.ingestion.image.repository "tag" .Values.ingestion.image.tag "Values" .Values) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "spending-monitor.fullname" . }}-secret
                  key: DATABASE_URL
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "spending-monitor.fullname" . }}-secret
                  key: API_KEY
            - name: ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: {{ include "spending-monitor.fullname" . }}-secret
                  key: ENVIRONMENT
            - name: DEBUG
              valueFrom:
                secretKeyRef:
                  name: {{ include "spending-monitor.fullname" . }}-secret
                  key: DEBUG
          {{- if .Values.ingestion.healthCheck.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.ingestion.healthCheck.path }}
              port: http
            initialDelaySeconds: {{ .Values.ingestion.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.ingestion.healthCheck.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.ingestion.healthCheck.path }}
              port: http
            initialDelaySeconds: {{ .Values.ingestion.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.ingestion.healthCheck.periodSeconds }}
          {{- end }}
          resources:
            {{- toYaml .Values.ingestion.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

