services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: spending-monitor
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d spending-monitor"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
